kind = "web"
previewPath = "/"
title = "Top Up Game"
version = "1.0.0"
id = "artifacts/topup-game"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24617

[services.development]
run = "npm --workspace=@workspace/topup-game run dev"

[services.production]
build = [ "npm", "--workspace=@workspace/topup-game", "run", "build" ]
publicDir = "artifacts/topup-game/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24617"
BASE_PATH = "/"
